# Default values for service-mesh-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespacePermissions:
  # Which OpenShift user gets permissions for the namespace
  user: kubeadmin
  # Which role to grant the user on the namespace
  role: admin